version: 2.1
orbs:
 node: circleci/node@5.0.2
 eb: circleci/aws-elastic-beanstalk@2.0.1
 aws-cli: circleci/aws-cli@3.1.1
 browser-tools: circleci/browser-tools@1.2.3
node: circleci/node@5.0.2
eb: circleci/aws-elastic-beanstalk@2.0.1
aws-cli: circleci/aws-cli@3.1.1
jobs:
build:
  working_directory: ~/ng-project
 docker:
   - image: "cimg/node:14.15"
 steps:
   - node/install
   - checkout
   - aws-cli/setup
   - browser-tools/install-chrome
   - browser-tools/install-chromedriver
   - run:
       name: Front-End Install
       command: |
         npm run frontend:install
   - run:
       name: Back-End Install
       command: |
         npm run backend:install
   - run:
       name: Front-End Build
       command: |
         npm run frontend:build
   - run:
       name: Back-End Build
       command: |
         npm run backend:build
   - run:
       name: Deploy App
       command: |
         npm run frontend:deploy    